# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chuck's Rants, Roamings, Reviews and Random Stuff
email: chuck.brant@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Chuck's corner of the internet where I'll post the random stuff that intersts me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chuckbrant.github.io" # the base hostname & protocol for your site
twitter_username: chuck_brant
github_username:  chuckbrant

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "photography"
    values:
      permalink: /:path/:basename:output_ext

exclude: [LICENSE-CODE.md, LICENSE-IMAGES, README.md, bower.json]

theme: jekyll-theme-tactile